#!/bin/bash

# CAR for collect and run

# CAR will collect all the prototypes of the unit tests
# and put them in a file collected.hpp then compile them with OBJS and OBJS_TEST

# Check if the file collected.hpp exists
if [ -f collected.hpp ]; then
	rm collected.hpp;
fi

echo "// This file is generated by CAR.sh" > collected.hpp;
echo "#ifndef COLLECTED_HPP" >> collected.hpp;
echo "# define COLLECTED_HPP" >> collected.hpp;
echo "" >> collected.hpp;
echo '# include "car.hpp"' >> collected.hpp;
echo "" >> collected.hpp;

# Collect all the prototypes of the unit tests
CPP_FILES=`find . -type f -name "*.cpp"`;
for file in $CPP_FILES; do
	echo "Collected file: $file";
	PROTO=`grep car_test $file`;
	N_PROTO=`echo "$PROTO" | wc -l`;
	echo $N_PROTO "prototypes founds";
	IFS=$'\n';
	for proto in $PROTO; do
		echo "	$proto; // $file" >> collected.hpp;
		echo ${proto} | cut -d ' ' -f2 | cut -d '(' -f1;
	done
done

echo "" >> collected.hpp;
echo "#endif" >> collected.hpp;
